# Assignment 1

![](https://media.giphy.com/media/xT9C25UNTwfZuk85WP/giphy-downsized-large.gif)

Remember the rules of ~Fight~ Code Club:
1. ALWAYS DOCUMENT
2. Cite resources that you use (paste links)
3. Include the names people who you worked with
4. Be neat and organized

## Scrape and Clean data

Based on you proposal, scrape or collect your data:

1. One variable must be either: (40 pts)
    1. scraped from the web OR;
    2. collected from an API AND you must create one new variable that is "new" to the best of your knowledge (combination of other variables representing something new).

2. You must have at least 3 variables, but you may include as many as you want into you final dataset. Likely, you will want to include more to make graphs and regressions. (30pts)

3. You must *be able* to run a regression that makes some sense with this data (the regression doesn't have to be a complete model). Briefly describe one regression you would run with your variables. (**DO NOT** run a regression, yet). (15pts)

4. You must have one combined and cleaned dataset (15 pts)

You must submit one python notebook on how you scraped/gathered data from an api, and how you combined and cleaned you data. I should be able to run your code and reproduce your final data set.  

The other variables that you choose to include do not have to be collected by API or webscraped, but you do have to combine the files and clean the dataset with python.

Thus, you must submit:
- Your finalized data set (only one) (note: you may add more variables in the future).
- Your documented python notebook
- Any associated data files needed to produce the final dataset.

You will be evaluated on:
- Completeness of the data
- Quality of the code 
- The creativity of the new variable/webscraped data you gather

Be sure to upload ALL associated files for your code to run. I will run your code from beginning to end - make it easy for me to replicate your code.

Sources Used: 
1. "C:\Users\laura\OneDrive\Documents\ECO590\Data_Analysis_Python_R\New Data City Access Granted\Lecture 4.ipynb" (Lecture 4 Notes)
2. "C:\Users\laura\OneDrive\Documents\ECO590\Data_Analysis_Python_R\Lets get this data started  Pandas\Lecture 6.ipynb" (Lecture 6 Notes)
3. https://www.youtube.com/watch?v=JVQNywo4AbU (YouTube video)
4. https://www.youtube.com/watch?v=hpc5jyVpUpw (YouTube Video)
5. https://stackoverflow.com/questions/61977076/how-to-fetch-data-from-api-using-python

In [1]:
#Import packages into python 
import requests #imports the requests into python 
import pandas as pd #imports pandas into python

In [2]:
#Get data from CoinGecko API 
url = "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd" #link of CoinGecko API (where I get the crypto data)

#settings for the API request 
params = {
    "vs_currency": "usd", #get prices in US dollars
    "order": "market_cap_desc", #sort coins by biggest market cap first
    "per_page": 50, #gets the top 50 cryptocurrencies
    "page": 1, #first page of results
    "sparkline": False, #do not need extra graph data 
    "price_change_percentage": "24h" #include 24-hour price change % 
}

response = requests.get(url, params=params) #sends request to the API and gets the data

data = response.json() #converts the response into JSON format 

df = pd.DataFrame(data) #turns the data into a pandas dataframe 

df.head() #gives us the frist 5 rows of the dataset

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated,price_change_percentage_24h_in_currency
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,71236.000000,1424373946458,1,1424373946458,3.592665e+10,71922.000000,...,2.100000e+07,126080.00,-43.49936,2025-10-06T18:57:42.558Z,67.810000,1.049538e+05,2013-07-06T00:00:00.000Z,None,2026-03-26T01:23:52.231Z,0.685156
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2163.620000,261000900686,2,261000900686,1.570007e+10,2196.430000,...,NaN,4946.05,-56.25556,2025-08-24T19:21:03.333Z,0.432979,4.996060e+05,2015-10-20T00:00:00.000Z,"{'times': 39.605961850807496, 'currency': 'btc...",2026-03-26T01:23:53.204Z,0.161446
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999613,184143769942,3,189608548886,6.133658e+10,0.999828,...,NaN,1.32,-24.44914,2018-07-24T00:00:00.000Z,0.572521,7.459795e+01,2015-03-02T00:00:00.000Z,None,2026-03-26T01:23:51.572Z,0.004005
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,646.290000,88107189997,4,88107189997,9.963930e+08,652.090000,...,2.000000e+08,1369.99,-52.82526,2025-10-13T08:41:24.131Z,0.039818,1.623022e+06,2017-10-19T00:00:00.000Z,None,2026-03-26T01:23:52.062Z,1.055905
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.410000,86576589402,5,141111406594,1.856525e+09,1.430000,...,1.000000e+11,3.65,-61.29748,2025-07-18T03:40:53.808Z,0.002686,5.243655e+04,2014-05-22T00:00:00.000Z,None,2026-03-26T01:23:49.938Z,-0.412900

In [3]:
#Keep only the columns that I need for this project 
df = df[['name', 'current_price', 'market_cap', 'total_volume', 'price_change_percentage_24h']] #keeps only the columns that is needed for this project 
df.head() #prints the first 5 rows of the new dataset

,name,current_price,market_cap,total_volume,price_change_percentage_24h
0,Bitcoin,71236.000000,1424373946458,3.592665e+10,0.68516
1,Ethereum,2163.620000,261000900686,1.570007e+10,0.16145
2,Tether,0.999613,184143769942,6.133658e+10,0.00400
3,BNB,646.290000,88107189997,9.963930e+08,1.05591
4,XRP,1.410000,86576589402,1.856525e+09,-0.41290

In [4]:
#The new calculated variable (Price Volatility) 
df['price_volatility'] = df['price_change_percentage_24h'].abs() #creates the price volatility variable using absolute value of 24h price change 
df.head() #prints the first 5 columns

,name,current_price,market_cap,total_volume,price_change_percentage_24h,price_volatility
0,Bitcoin,71236.000000,1424373946458,3.592665e+10,0.68516,0.68516
1,Ethereum,2163.620000,261000900686,1.570007e+10,0.16145,0.16145
2,Tether,0.999613,184143769942,6.133658e+10,0.00400,0.00400
3,BNB,646.290000,88107189997,9.963930e+08,1.05591,1.05591
4,XRP,1.410000,86576589402,1.856525e+09,-0.41290,0.41290

In [5]:
#Cleaning the dataset 
df = df.dropna() #removes rows that have missing data 
df.info() #checks the data type of each column 
df.head() #prints the first 5 rows

<class 'pandas.core.frame.DataFrame'>
Index: 49 entries, 0 to 49
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         49 non-null     object
 1   current_price                49 non-null     float64
 2   market_cap                   49 non-null     int64
 3   total_volume                 49 non-null     float64
 4   price_change_percentage_24h  49 non-null     float64
 5   price_volatility             49 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.7+ KB

,name,current_price,market_cap,total_volume,price_change_percentage_24h,price_volatility
0,Bitcoin,71236.000000,1424373946458,3.592665e+10,0.68516,0.68516
1,Ethereum,2163.620000,261000900686,1.570007e+10,0.16145,0.16145
2,Tether,0.999613,184143769942,6.133658e+10,0.00400,0.00400
3,BNB,646.290000,88107189997,9.963930e+08,1.05591,1.05591
4,XRP,1.410000,86576589402,1.856525e+09,-0.41290,0.41290

In [6]:
#Saving the dataset as a CSV file 
df.to_csv("crypto_data.csv", index=False)

In [7]:
pd.read_csv("crypto_data.csv").head() #double checking the file was created

,name,current_price,market_cap,total_volume,price_change_percentage_24h,price_volatility
0,Bitcoin,71236.000000,1424373946458,3.592665e+10,0.68516,0.68516
1,Ethereum,2163.620000,261000900686,1.570007e+10,0.16145,0.16145
2,Tether,0.999613,184143769942,6.133658e+10,0.00400,0.00400
3,BNB,646.290000,88107189997,9.963930e+08,1.05591,1.05591
4,XRP,1.410000,86576589402,1.856525e+09,-0.41290,0.41290

Regression Explanation: I am going to run a regression where price volatility is the dependent variable, and trading volume and market capitalization are the independent variables. This would help me analyze how market activity and size can affect cryptocurrency price fluctuations.